# PlayerTags config file

# If true only the highest priority tag will be shown
highest_priority_only: false

# Color for players who have not chosen a color
default_color: "GRAY"

# Year badge settings
year_badge:
  # Set to false to disable year badges globally.
  enabled: true

  # Yearbadge tag priority (used when sorting)
  priority: 0

  # Year badge for chat
  chat_tag: "○"

  # Year badge for player list
  list_tag: "○"

# List of custom tags
tags:
  mod:
    # Set to false to skip loading this tag
    enabled: true

    # Priority in sorting.  Higher numbers are more important
    priority: 1

    # Tag that will be shown next to player name in chat
    chat_tag: "∆"

    # Tag that will be show next to player name in player list
    list_tag: "∆"

    # Permission node required to apply this tag
    permission: "rank.mod"
  admin:
    # Set to false to skip loading this tag
    enabled: true

    # Priority in sorting.  Higher numbers are more important
    priority: 2

    # Tag that will be shown next to player name in chat
    chat_tag: "□"

    # Tag that will be show next to player name in player list
    list_tag: "□"

    # Permission node required to apply this tag
    permission: "rank.admin"